@baseURL = http://localhost:3000
@userId = 10
@eventId = 7
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzYwNDQzODUxLCJleHAiOjE3NjA0NDc0NTF9.5OcR8CWaFjSBrAoEAPMHQJ3QMR13A3GE7Qq3cN35FbE

#########################
##### Public routes #####
#########################

### Display Events
GET {{baseURL}}/events/
Content-Type: application/json

### Admin user authentication
POST {{baseURL}}/auth/login/
Content-Type: application/json

{
"email": "admin@example.com",
"password": "senha123"
}

### Volunteer user authentication
POST {{baseURL}}/auth/login/
Content-Type: application/json

{
"email": "volunteer@example.com",
"password": "senha123"
}

### Register user
POST {{baseURL}}/auth/register
Content-Type: application/json
'""
{
    "name": "Jane Doe",
    "email": "jane.doe@example.com",  
    "password": "senha123",
    "role": "admin"
}

### Register user with invalid role
POST {{baseURL}}/auth/register
Content-Type: application/json

{
    "name": "Jonathan Jones",
    "email": "jonathan.jones@example.com",
    "password": "senha123",
    "role": "moderator"
}

### Register user with no role (will assign default "volunteer")
POST {{baseURL}}/auth/register
Content-Type: application/json

{
    "name": "John Smith",
    "email": "john.smith@example.com",
    "password": "senha123"
}

##########################
#### Protected routes ####
##########################

# ### Dashboard
# GET {{baseURL}}/dashboard
# Content-Type: application/json
# Authorization: Bearer {{token}}

######### Events ########

### Get event
GET {{baseURL}}/events/
Content-Type: application/json

### Create Event
POST {{baseURL}}/events/
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Community Clean-up",
  "description": "Join us to clean the neighborhood park.",
  "date": "2025-10-20",
  "location": "Central Park",
  "max_volunteers": "100"
}

### Update event
PUT {{baseURL}}/events/{{eventId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Updated Community Clean-up",
  "description": "Join us to clean the downtown park.",
  "date": "2025-10-22",
  "location": "Downtown Park",
  "max_volunteers": 120
}

### Delete event
DELETE {{baseURL}}/events/{{eventId}}
Content-Type: application/json
Authorization: Bearer {{token}}

######### Users ########

### Get users
GET {{baseURL}}/users
Content-Type: application/json
Authorization: Bearer {{token}}

### Get user by id
GET {{baseURL}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

### Update user
PUT {{baseURL}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Jane aaaaaa",
  "email": "jane.3232@example.com",
  "password": "newpassword123",
  "role": "admin"
}

### Delete user
DELETE {{baseURL}}/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{token}}
